#!/bin/sh

scale=$(</sys/bus/iio/devices/iio:device0/in_voltage_scale)
in0=$(</sys/bus/iio/devices/iio:device0/in_voltage0_raw)
in1=$(</sys/bus/iio/devices/iio:device0/in_voltage1_raw)
in2=$(</sys/bus/iio/devices/iio:device0/in_voltage2_raw)
in3=$(</sys/bus/iio/devices/iio:device0/in_voltage3_raw)

echo resolution = $scale [mV/bit]
echo ana0raw = $in0 [bit]
echo ana1raw = $in1 [bit]
echo ana2raw = $in2 [bit]
echo ana3raw = $in3 [bit]

ana0=$(echo $scale $in0 | awk '{printf "%4.3f\n",$1*$2}')
ana1=$(echo $scale $in1 | awk '{printf "%4.3f\n",$1*$2}')
ana2=$(echo $scale $in2 | awk '{printf "%4.3f\n",$1*$2}')
ana3=$(echo $scale $in3 | awk '{printf "%4.3f\n",$1*$2}')

echo ana0 = $ana0 mV
echo ana1 = $ana1 mV
echo ana2 = $ana2 mV
echo ana3 = $ana3 mV


