#!/bin/sh
cd /home/root
mkdir -p gpio
cd gpio

find -type l -exec rm -rf {} \;

#===========================================
#   GPIO OUTPUT DD1
#===========================================
#EIM_LBA__GPIO2_IO27  K22  SPARE_1_OUT_CPU - 59
echo 59 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio59/direction
echo 1 > /sys/class/gpio/gpio59/value
ln -sf /sys/class/gpio/gpio59/value OUT_SPARE_1_OUT_CPU

#EIM_OE__GPIO2_IO25   J24  SPARE_3_OUT_CPU - 57
echo 57 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio57/direction
echo 1 > /sys/class/gpio/gpio57/value
ln -sf /sys/class/gpio/gpio57/value OUT_SPARE_3_OUT_CPU

#EIM_RW__GPIO2_IO26   K20  SPARE_2_OUT_CPU - 58
echo 58 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio58/direction
echo 1 > /sys/class/gpio/gpio58/value
ln -sf /sys/class/gpio/gpio58/value OUT_SPARE_2_OUT_CPU

#EIM_CS0__GPIO2_IO23  H24  RESET_ADC_CPU - 55
echo 55 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio55/direction
echo 1 > /sys/class/gpio/gpio55/value
ln -sf /sys/class/gpio/gpio55/value OUT_RESET_ADC_CPU

#EIM_CS1__GPIO2_IO24  J23  SKR_PWR_CTR_CPU - 56
echo 56 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio56/direction
echo 0 > /sys/class/gpio/gpio56/value
ln -sf /sys/class/gpio/gpio56/value OUT_SKR_PWR_CTR_CPU

#EIM_A16__GPIO2_IO22  H25  EASAU_CPU - 54
echo 54 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio54/direction
echo 0 > /sys/class/gpio/gpio54/value
ln -sf /sys/class/gpio/gpio54/value OUT_EASAU_CPU

#EIM_A17__GPIO2_IO21  G24  EEO_CPU - 53
echo 53 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio53/direction
echo 0 > /sys/class/gpio/gpio53/value
ln -sf /sys/class/gpio/gpio53/value OUT_EEO_CPU

#EIM_A18__GPIO2_IO20  J22  ESS_CPU - 52
echo 52 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio52/direction
echo 0 > /sys/class/gpio/gpio52/value
ln -sf /sys/class/gpio/gpio52/value OUT_ESS_CPU

#EIM_A19__GPIO2_IO19  G25  EPA_CPU - 51
echo 51 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio51/direction
echo 0 > /sys/class/gpio/gpio51/value
ln -sf /sys/class/gpio/gpio51/value OUT_EPA_CPU

#EIM_A20__GPIO2_IO18  H22  EDB_CPU - 50
echo 50 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio50/direction
echo 0 > /sys/class/gpio/gpio50/value
ln -sf /sys/class/gpio/gpio50/value OUT_EDB_CPU

#EIM_A21__GPIO2_IO17  H23  EFB_CPU - 49
echo 49 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio49/direction
echo 0 > /sys/class/gpio/gpio49/value
ln -sf /sys/class/gpio/gpio49/value OUT_EFB_CPU

#EIM_A22__GPIO2_IO16  F24  EAB_CPU - 48
echo 48 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio48/direction
echo 0 > /sys/class/gpio/gpio48/value
ln -sf /sys/class/gpio/gpio48/value OUT_EAB_CPU

#EIM_A23__GPIO6_IO06  J21  GPIO6_06_UNUSED - 166
echo 166 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio166/direction
echo 0 > /sys/class/gpio/gpio166/value
ln -sf /sys/class/gpio/gpio166/value OUT_GPIO6_06_UNUSED

#EIM_A24__GPIO5_IO04  F25  INH_SORVOLO_CPU - 132
echo 132 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio132/direction
echo 0 > /sys/class/gpio/gpio132/value
ln -sf /sys/class/gpio/gpio132/value OUT_INH_SORVOLO_CPU

#EIM_A25__GPIO5_IO02  H19  EBT_CPU - 130
echo 130 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio130/direction
echo 0 > /sys/class/gpio/gpio130/value
ln -sf /sys/class/gpio/gpio130/value OUT_EBT_CPU

#EIM_D31__GPIO3_IO31  H21  UART3_RTS_B_CPU - 95
echo 95 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio95/direction
echo 0 > /sys/class/gpio/gpio95/value
ln -sf /sys/class/gpio/gpio95/value OUT_UART3_RTS_B_CPU

#EIM_EB2__GPIO2_IO30  E22  CMD_SPIRA_CPU - 62
echo 62 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio62/direction
echo 0 > /sys/class/gpio/gpio62/value
ln -sf /sys/class/gpio/gpio62/value OUT_CMD_SPIRA_CPU

#EIM_EB3__GPIO2_IO31  F23  INH_G_SWITCH_CPU - 63
echo 63 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio63/direction
echo 0 > /sys/class/gpio/gpio63/value
ln -sf /sys/class/gpio/gpio63/value OUT_INH_G_SWITCH_CPU

#EIM_BCLK__GPIO6_IO31 N22  EBT_SK_CPU - 191
echo 191 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio191/direction
echo 0 > /sys/class/gpio/gpio191/value
ln -sf /sys/class/gpio/gpio191/value OUT_EBT_SK_CPU

#EIM_WAIT__GPIO5_IO00 M25  BIT_L_CPU - 128
echo 128 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio128/direction
echo 0 > /sys/class/gpio/gpio128/value
ln -sf /sys/class/gpio/gpio128/value OUT_BIT_L_CPU

#EIM_EB0__GPIO2_IO28  K21  GPIO2_IO28_UNUSED - 60
echo 60 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio60/direction
echo 0 > /sys/class/gpio/gpio60/value
ln -sf /sys/class/gpio/gpio60/value OUT_GPIO2_IO28_UNUSED

#GPIO_2__GPIO1_IO02     T1  IT_UC - 2
echo 2 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio2/direction
echo 0 > /sys/class/gpio/gpio2/value
ln -sf /sys/class/gpio/gpio2/value OUT_IT_UC

#CSI0_PIXCLK__GPIO5_IO18  P1  ARM_EVENTO - 146
echo 146 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio146/direction
echo 0 > /sys/class/gpio/gpio146/value
ln -sf /sys/class/gpio/gpio146/value OUT_ARM_EVENTO

#CSI0_DATA_EN__GPIO5_IO20 P3  ARM_TRACE_CLK - 148
echo 148 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio148/direction
echo 0 > /sys/class/gpio/gpio148/value
ln -sf /sys/class/gpio/gpio148/value OUT_ARM_TRACE_CLK

#CSI0_VSYNC__GPIO5_IO21   N2  ARM_TRACE00 - 149
echo 149 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio149/direction
echo 0 > /sys/class/gpio/gpio149/value
ln -sf /sys/class/gpio/gpio149/value OUT_ARM_TRACE00

#CSI0_DAT4__GPIO5_IO22    N1  ARM_TRACE01 - 150
echo 150 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio150/direction
echo 0 > /sys/class/gpio/gpio150/value
ln -sf /sys/class/gpio/gpio150/value OUT_ARM_TRACE01

#CSI0_DAT5__GPIO5_IO23    P2  ARM_TRACE02 - 151
echo 151 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio151/direction
echo 0 > /sys/class/gpio/gpio151/value
ln -sf /sys/class/gpio/gpio151/value OUT_ARM_TRACE02

#CSI0_DAT6__GPIO5_IO24    N4  ARM_TRACE03 - 152
echo 152 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio152/direction
echo 0 > /sys/class/gpio/gpio152/value
ln -sf /sys/class/gpio/gpio152/value OUT_ARM_TRACE03

#CSI0_DAT7__GPIO5_IO25    N3  ARM_TRACE04 - 153
echo 153 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio153/direction
echo 0 > /sys/class/gpio/gpio153/value
ln -sf /sys/class/gpio/gpio153/value OUT_ARM_TRACE04

#CSI0_DAT8__GPIO5_IO26    N6  ARM_TRACE05 - 154
echo 154 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio154/direction
echo 0 > /sys/class/gpio/gpio154/value
ln -sf /sys/class/gpio/gpio154/value OUT_ARM_TRACE05

#CSI0_DAT9__GPIO5_IO27    N5  ARM_TRACE06 - 155
echo 155 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio155/direction
echo 0 > /sys/class/gpio/gpio155/value
ln -sf /sys/class/gpio/gpio155/value OUT_ARM_TRACE06

#CSI0_DAT10__GPIO5_IO28    M1  ARM_TRACE07 - 156
echo 156 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio156/direction
echo 0 > /sys/class/gpio/gpio156/value
ln -sf /sys/class/gpio/gpio156/value OUT_ARM_TRACE07

#DISP0_DAT8__GPIO4_IO29  R22  CMD_CONSENSOFUOCO_CPU - 125
#echo 125 > /sys/class/gpio/export
#echo out > /sys/class/gpio/gpio125/direction
#echo 0 > /sys/class/gpio/gpio125/value
#ln -sf /sys/class/gpio/gpio125/value OUT_CMD_CONSENSOFUOCO_CPU

#DISP0_DAT9__GPIO4_IO30  T25  CMD_FMP_INT_CPU - 126
echo 126 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio126/direction
echo 0 > /sys/class/gpio/gpio126/value
ln -sf /sys/class/gpio/gpio126/value OUT_CMD_FMP_INT_CPU

#DISP0_DAT11__GPIO5_IO05  T23  SENS_D00_CPU - 133
echo 133 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio133/direction
echo 0 > /sys/class/gpio/gpio133/value
ln -sf /sys/class/gpio/gpio133/value OUT_SENS_D00_CPU

#DISP0_DAT12__GPIO5_IO06  T24  SENS_D01_CPU - 134
echo 134 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio134/direction
echo 0 > /sys/class/gpio/gpio134/value
ln -sf /sys/class/gpio/gpio134/value OUT_SENS_D01_CPU

#DISP0_DAT13__GPIO5_IO07  R20  OK_CPU - 135
echo 135 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio135/direction
echo 0 > /sys/class/gpio/gpio135/value
ln -sf /sys/class/gpio/gpio135/value OUT_OK_CPU

#DISP0_DAT14__GPIO5_IO08  U25  GO_SW_CPU - 136
echo 136 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio136/direction
echo 0 > /sys/class/gpio/gpio136/value
ln -sf /sys/class/gpio/gpio136/value OUT_GO_SW_CPU

#DISP0_DAT16__GPIO5_IO10  T21  SEL_ANT_CPU - 138
echo 138 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio138/direction
echo 0 > /sys/class/gpio/gpio138/value
ln -sf /sys/class/gpio/gpio138/value OUT_SEL_ANT_CPU

#DISP0_DAT17__GPIO5_IO11  U24  RESET_L_CPU - 139
echo 139 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio139/direction
echo 0 > /sys/class/gpio/gpio139/value
ln -sf /sys/class/gpio/gpio139/value OUT_RESET_L_CPU

#KEY_ROW4__GPIO4_IO15  V5  USB_OTGPWR_EN - 111
echo 111 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio111/direction
echo 0 > /sys/class/gpio/gpio111/value
ln -sf /sys/class/gpio/gpio111/value OUT_USB_OTGPWR_EN

#GPIO_17__GPIO7_IO12  R1  GPIO7_12_UNUSED - 204
echo 204 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio204/direction
echo 0 > /sys/class/gpio/gpio204/value
ln -sf /sys/class/gpio/gpio204/value OUT_GPIO7_12_UNUSED

#GPIO_19__GPIO4_IO05  P5  IMX6_SPARE_LED - 101
echo 101 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio101/direction
echo 0 > /sys/class/gpio/gpio101/value
ln -sf /sys/class/gpio/gpio101/value OUT_IMX6_SPARE_LED

#NANDF_D0__GPIO2_IO00  A18  TFUEL_RANGE_SLC - 32
echo 32 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio32/direction
echo 0 > /sys/class/gpio/gpio32/value
ln -sf /sys/class/gpio/gpio32/value OUT_TFUEL_RANGE_SLC

#NANDF_D1__GPIO2_IO01  C17  MAINT_SK_CPU - 33
echo 33 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio33/direction
echo 0 > /sys/class/gpio/gpio33/value
ln -sf /sys/class/gpio/gpio33/value OUT_MAINT_SK_CPU

#NANDF_D2__GPIO2_IO02  F16  ID_00_CPU - 34
echo 34 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio34/direction
echo 0 > /sys/class/gpio/gpio34/value
ln -sf /sys/class/gpio/gpio34/value OUT_ID_00_CPU

#NANDF_D3__GPIO2_IO03  D17  ID_01_CPU - 35
echo 35 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio35/direction
echo 0 > /sys/class/gpio/gpio35/value
ln -sf /sys/class/gpio/gpio35/value OUT_ID_01_CPU

#NANDF_D4__GPIO2_IO04  A19  SAFE_SPOLETTA_CPU - 36
echo 36 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio36/direction
echo 0 > /sys/class/gpio/gpio36/value
ln -sf /sys/class/gpio/gpio36/value OUT_SAFE_SPOLETTA_CPU

#NANDF_D5__GPIO2_IO05  B18  ENABLE_DL_CPU - 37
echo 37 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio37/direction
echo 0 > /sys/class/gpio/gpio37/value
ln -sf /sys/class/gpio/gpio37/value OUT_ENABLE_DL_CPU

#NANDF_D6__GPIO2_IO06  E17  ESA_CPU - 38
echo 38 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio38/direction
echo 0 > /sys/class/gpio/gpio38/value
ln -sf /sys/class/gpio/gpio38/value OUT_ESA_CPU

#NANDF_D7__GPIO2_IO07  C18  ESF_CPU - 39
echo 39 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio39/direction
echo 0 > /sys/class/gpio/gpio39/value
ln -sf /sys/class/gpio/gpio39/value OUT_ESF_CPU

#KEY_ROW1__GPIO4_IO09   ECSPI1_UC_SS0  - 105//NON SETTARE COME OUTPUT SPI1_CS0 AUTOMATICO
#echo 105 > /sys/class/gpio/export
#echo out > /sys/class/gpio/gpio105/direction
#echo 1 > /sys/class/gpio/gpio105/value
#ln -sf /sys/class/gpio/gpio105/value OUT_ECSPI1_UC_SS0

#DISP0_DAT3__GPIO4_IO24  P21  ECSPI3_SS0 - 120
echo 120 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio120/direction
echo 1 > /sys/class/gpio/gpio120/value
ln -sf /sys/class/gpio/gpio120/value OUT_ECSPI3_SS0

#DISP0_DAT4__GPIO4_IO25  P20  ECSPI3_SS1 - 121
echo 121 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio121/direction
echo 1 > /sys/class/gpio/gpio121/value
ln -sf /sys/class/gpio/gpio121/value OUT_ECSPI3_SS1

#DISP0_DAT5__GPIO4_IO26  R25  ECSPI3_SS2 - 122
echo 122 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio122/direction
echo 1 > /sys/class/gpio/gpio122/value
ln -sf /sys/class/gpio/gpio122/value OUT_ECSPI3_SS2

#DISP0_DAT6__GPIO4_IO27  R23  ECSPI3_SS3 - 123
echo 123 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio123/direction
echo 1 > /sys/class/gpio/gpio123/value
ln -sf /sys/class/gpio/gpio123/value OUT_ECSPI3_SS3

#EIM_D20__GPIO3_IO20  G20  ECSPI4_SS0 - 84
echo 84 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio84/direction
echo 1 > /sys/class/gpio/gpio84/value
ln -sf /sys/class/gpio/gpio84/value OUT_ECSPI4_SS0

#SD1_DAT1__GPIO1_IO17  C20  ECSPI5_SS0 - 17
echo 17 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio17/direction
echo 1 > /sys/class/gpio/gpio17/value
ln -sf /sys/class/gpio/gpio17/value OUT_ECSPI5_SS0

#SD1_DAT2__GPIO1_IO19  E19  ECSPI5_SS1 - 19
echo 19 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio19/direction
echo 1 > /sys/class/gpio/gpio19/value
ln -sf /sys/class/gpio/gpio19/value OUT_ECSPI5_SS1

#SD1_DAT3__GPIO1_IO21  F18  ECSPI5_SS2 - 21
echo 21 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio21/direction
echo 1 > /sys/class/gpio/gpio21/value
ln -sf /sys/class/gpio/gpio21/value OUT_ECSPI5_SS2

#SD2_DAT3__GPIO1_IO12  B22  ECSPI5_SS3 - 12
echo 12 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio12/direction
echo 1 > /sys/class/gpio/gpio12/value
ln -sf /sys/class/gpio/gpio12/value OUT_ECSPI5_SS3




#===========================================
#   GPIO INPUT DD1
#===========================================				
#EIM_D26__GPIO3_IO26   E24 SPARE_1_IN_CPU - 90
echo 90 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio90/value IN_SPARE_1_IN_CPU

#EIM_D19__GPIO3_IO19   G21 SPARE_2_IN_CPU - 83
echo 83 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio83/value IN_SPARE_2_IN_CPU

#EIM_D27__GPIO3_IO27   E25 SPARE_3_IN_CPU - 91
echo 91 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio91/value IN_SPARE_3_IN_CPU

#EIM_D23__GPIO3_IO23   D25 UART3_CTS_B_CPU - 87
echo 87 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio87/value IN_UART3_CTS_B_CPU

#EIM_D29__GPIO3_IO29   J19 CK_PLUG_0_CPU - 93
echo 93 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio93/value IN_CK_PLUG_0_CPU

#EIM_D29__GPIO3_IO30   J20 CK_PLUG_1_CPU - 94
echo 94 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio94/value IN_CK_PLUG_1_CPU

#CSI0_MCLK__GPIO5_IO19     P4  ARM_TRACE_CTL - 147
echo 147 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio147/value IN_ARM_TRACE_CTL

#CSI0_DAT11__GPIO5_IO29    M3  ARM_TRACE08 - 157
echo 157 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio157/value IN_ARM_TRACE08

#CSI0_DAT12__GPIO5_IO30    M2  ARM_TRACE09 - 158
echo 158 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio158/value IN_ARM_TRACE09

#CSI0_DAT13__GPIO5_IO31    L1  ARM_TRACE10 - 159
echo 159 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio159/value IN_ARM_TRACE10

#CSI0_DAT14__GPIO6_IO00    M4  ARM_TRACE11 - 160
echo 160 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio160/value IN_ARM_TRACE11

#CSI0_DAT15__GPIO6_IO01    M5  ARM_TRACE12 - 161
echo 161 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio161/value IN_ARM_TRACE12

#CSI0_DAT16__GPIO6_IO02    L4  ARM_TRACE13 - 162
echo 162 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio162/value IN_ARM_TRACE13

#CSI0_DAT17__GPIO6_IO03    L3  ARM_TRACE14 - 163
echo 163 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio163/value IN_ARM_TRACE14

#CSI0_DAT18__GPIO6_IO04    M6  ARM_TRACE15 - 164
echo 164 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio164/value IN_ARM_TRACE15

#GPIO_5__GPIO1_IO05        R4  ARM_EVENTI  - 5
echo 5 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio5/value IN_ARM_EVENTI

#CSI0_DAT19__GPIO6_IO05    L6    SPARE2_ARTIX7 - 165
echo 165 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio165/value IN_SPARE2_ARTIX7

#DI0_DISP_CLK__GPIO4_IO16  N19   CK_PRES_BT2_CPU - 112
echo 112 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio112/value IN_CK_PRES_BT2_CPU

#DI0_PIN15__GPIO4_IO17     N21   OK_GPS_CPU - 113
echo 113 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio113/value IN_OK_GPS_CPU

#DI0_PIN2__GPIO4_IO18      N25   OK_SPOLETTA_CPU - 114
echo 114 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio114/value IN_OK_SPOLETTA_CPU

#DI0_PIN3__GPIO4_IO19      N20   OK_DL_CPU - 115
echo 115 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio115/value IN_OK_DL_CPU

#DI0_PIN4__GPIO4_IO20      P25   OK_PS_TH_CPU - 116
echo 116 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpioXX/value IN_OK_PS_TH_CPU

#DISP0_DAT7__GPIO4_IO28    R24   STATUS_ANT_CPU - 124
echo 124 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpioXX/value IN_STATUS_ANT_CPU

#DISP0_DAT10__GPIO4_IO31   R21   OK_PS_SWRF_CPU - 127
echo 127 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio127/value IN_OK_PS_SWRF_CPU

#DISP0_DAT18__GPIO5_IO12   V25   LOOPBACK_SIGNAL_CPU - 140
echo 140 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio140/value IN_LOOPBACK_SIGNAL_CPU

#DISP0_DAT19__GPIO5_IO13   U23   OK_BT_SK_PSB_CPU - 141
echo 141 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio141/value IN_OK_BT_SK_PSB_CPU

#DISP0_DAT20__GPIO5_IO14   U22   OK_PS_WCU_CPU - 142
echo 142 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio142/value IN_OK_PS_WCU_CPU

#DISP0_DAT21__GPIO5_IO15   T20   GO_HW_CPU - 143
echo 143 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio143/value IN_GO_HW_CPU

#DISP0_DAT22__GPIO5_IO16   V24   GO_NOGO_MSL_CPU - 144
echo 144 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio1/value IN_GO_NOGO_MSL_CPU

#DISP0_DAT23__GPIO5_IO17   W24   GO_NOGO_UA_CPU - 145
echo 145 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio145/value IN_GO_NOGO_UA_CPU

#GPIO_4__GPIO1_IO04     R6  IT_SL_1 - 4
echo 4 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio4/value IN_IT_SL_1

#GPIO_7__GPIO1_IO07     R3  IT_SL_2 - 7
echo 7 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio7/value IN_IT_SL_2

#GPIO_8__GPIO1_IO08     R5  IT_SL_3 - 8
echo 8 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio8/value IN_IT_SL_3

#GPIO_9__GPIO1_IO09     T2  IT_SL_4 - 9
echo 9 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio9/value IN_IT_SL_4

#SD2_CMD__GPIO1_IO11   F19   IT_SL_5 - 11
echo 11 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio11/value IN_IT_SL_5

#SD2_CLK__GPIO1_IO10   C21   IT_SL_6 - 10
echo 10 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio10/value IN_IT_SL_6

#SD2_DAT0__GPIO1_IO15  A22   IT_SL_7 - 15
echo 15 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio15/value IN_IT_SL_7

#SD2_DAT1__GPIO1_IO14  E20   IT_SL_8 - 14
echo 14 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio14/value IN_IT_SL_8

#SD2_DAT2__GPIO1_IO13  A23   IT_SL_10 - 13
echo 13 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio13/value IN_IT_SL_10

#ENET_CRS_DV__GPIO1_IO25  U21   FAILSAFE_ENABLE_CPU - 25
echo 25 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio25/value IN_FAILSAFE_ENABLE_CPU

#ENET_RX_ER__GPIO1_IO24   W23   CK_BT2_CPU - 24
echo 24 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio24/value IN_CK_BT2_CPU

#ENET_TX_EN__GPIO1_IO28   V21   TB2_CPU - 28
echo 28 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio28/value IN_TB2_CPU

#ENET_RXD0__GPIO1_IO27    W21   OK_TIMER_CPU - 27
echo 27 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio27/value IN_OK_TIMER_CPU

#ENET_RXD1__GPIO1_IO26    W22   TELLBACKBT1_CPU - 26
echo 26 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio26/value IN_TELLBACKBT1_CPU

#ENET_TXD0__GPIO1_IO30    U20   FUS_BT1_CPU - 30
echo 30 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio30/value IN_FUS_BT1_CPU

#ENET_TXD1__GPIO1_IO29    W20   FUS_BT2_CPU - 29
echo 29 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio29/value IN_FUS_BT2_CPU

#KEY_COL0__GPIO4_IO06  W5  GPIO4_IO06_UNUSED - 102
echo 102 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio102/value GPIO4_IO06_UNUSED

#KEY_ROW0__GPIO4_IO07     V6    PB_SX_CPU - 103
echo 103 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio103/value IN_PB_SX_CPU

#KEY_COL1__GPIO4_IO08     U7    PB_DX_CPU - 104
echo 104 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio104/value IN_PB_DX_CPU

#KEY_COL2__GPIO4_IO10     W6    GO_SC_CPU - 106
echo 106 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio106/value IN_GO_SC_CPU

#KEY_ROW2__GPIO4_IO11     W4    FUS_SK_CPU - 107
echo 107 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio107/value IN_FUS_SK_CPU

#KEY_COL3__GPIO4_IO12     U5    SPARE1_ARTIX7 - 108
echo 108 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio108/value IN_SPARE1_ARTIX7

#KEY_ROW3__GPIO4_IO13     T7    T0_MSL_CPU - 109
echo 109 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio109/value IN_T0_MSL_CPU

#KEY_COL4__GPIO4_IO14     T6    USB_OTG_OC - 110
echo 110 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio110/value IN_USB_OTG_OC

#GPIO_0__GPIO1_IO00     T5      MAINT_SEL_CPU - 0
echo 0 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio0/value IN_MAINT_SEL_CPU

#GPIO_1__GPIO1_IO01     T4      USB_OTG_ID - 1
echo 1 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio1/value IN_USB_OTG_ID

#GPIO_16__GPIO7_IO11    R2     OK_TH_CPU - 203
echo 203 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio203/value IN_OK_TH_CPU

#GPIO_18__GPIO7_IO13    P6    TELLBACKBT2_CPU - 205
echo 205 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio205/value IN_TELLBACKBT2_CPU

#NANDF_CS0__GPIO6_IO11  F15    STATO_D2_CPU - 171
echo 171 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio171/value IN_STATO_D2_CPU

#NANDF_CS0__GPIO6_IO14  C16    TERMINATE_CMD_1_CPU - 174
echo 174 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio174/value IN_TERMINATE_CMD_1_CPU

#NANDF_CS0__GPIO6_IO15  A17    TERMINATE_CMD_2_CPU - 175
echo 175 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio175/value TERMINATE_CMD_2_CPU

#NANDF_CS0__GPIO6_IO16  D16    STATO_D1_CPU - 176
echo 176 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio176/value IN_STATO_D1_CPU

#NANDF_WP_B__GPIO6_IO09  E15    CTR_TELLBACKBT2_CPU - 169
echo 169 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio169/value IN_CTR_TELLBACKBT2_CPU

#NANDF_RB0__GPIO6_IO10  B16    T0_CONN_CPU - 170
echo 170 > /sys/class/gpio/export
ln -sf /sys/class/gpio/gpio170/value IN_T0_CONN_CPU




cd /home/root
./blink_led &
./udp_server &
